expenses/expense_manager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'addExpense/$', views.expense_form, name='expensesForm'),
    url(r'uploadFile/$', views.file_upload, name='uploadFile'),
    url(r'listExpense/$', views.view_expenses, name='expenseList'),
    url(r'addFile/$', views.add_file, name='addFile')
]

expenses/expenses/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^expenses/', include('expense_manager.urls')),
    url(r'', include('expense_manager.urls')),
    url(r'^admin/', admin.site.urls),
]

expenses/expense_manager/models.py
from django.db import models
from django.utils import timezone


class Portfolio(models.Model):
    class Meta:
        unique_together = (('first_name', 'last_name'),)

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    started_working = models.DateField("Date of Hire", null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


class ExpenseType(models.Model):
    name = models.CharField(max_length=255)
    is_haamasot_expense = models.BooleanField()

    def __str__(self):
        return self.name


class Expense(models.Model):
    portfolio = models.ForeignKey(Portfolio)
    expense_type = models.ForeignKey(ExpenseType)
    ammount = models.FloatField()
    date = models.DateField("Expense Date")

    def __str__(self):
        return self.expense_type.name + " Expense for " + self.portfolio.first_name + " " + self.portfolio.last_name + " - " + self.date.strftime("%d/%m/%y") + " - " + str(self.ammount) + "₪"

expenses/expense_manager/forms.py
from django import forms
from functools import partial
import openpyxl

from . import models


class NewExpenseForm(forms.ModelForm):
    class Meta:
        model = models.Expense
        fields = ['portfolio', 'expense_type', 'ammount', 'date']

    def __init__(self, *args, **kwargs):
        super(NewExpenseForm, self).__init__(*args, **kwargs)
        self.fields['portfolio'].widget.attrs.update({'class': 'w3-input w3-border w3-light-grey'})
        self.fields['expense_type'].widget.attrs.update({'class': 'w3-input w3-border w3-light-grey'})
        self.fields['ammount'].widget.attrs.update({'class': 'w3-input w3-border w3-light-grey'})
        self.fields['date'].widget.attrs.update({'class': 'w3-input w3-border w3-light-grey', 'type': 'date'})


class UploadFileForm(forms.Form):
    file = forms.FileField()

    def clean_file(self):
        file = self.cleaned_data['file']
        try:
            openpyxl.load_workbook(file)
        except:
            raise forms.ValidationError("Not an excel file")

expenses/expense_manager/views.py
import openpyxl
import datetime
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.utils import timezone
from django.contrib import messages
from . import forms
from . import models
import pandas
import bs4


def index(request):
    return render(request, 'expense_manager/expense_manager_base_layout.html')


def view_expenses(request):
    expenses = models.Expense.objects.all()
    portfolios = models.Portfolio.objects.all()
    data = []
    for expense in expenses:
        expense_fields_dict = {'portfolio': expense.portfolio.first_name + " " + expense.portfolio.last_name, 'expense_type': expense.expense_type.name, 'ammount': expense.ammount, 'date': expense.date}
        data.append(expense_fields_dict)
    table = pandas.DataFrame(data=data)[['portfolio', 'date', 'expense_type', 'ammount']].to_html(index=False, classes='myTable')
    beautifulSoupTable = bs4.BeautifulSoup(table)
    beautifulSoupTable.find('table')['class'] = 'pure-table w3-animate-top'
    beautifulSoupTable.find('table')['id'] = 'myTable'
    beautifulSoupTable = str(beautifulSoupTable)
    return render(request, 'expense_manager/expense_list.html', {'table': beautifulSoupTable, 'portfolios': portfolios})


@login_required
def expense_form(request):
    form = forms.NewExpenseForm()

    if request.method == 'POST':
        form = forms.NewExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Expense Added")
            return HttpResponseRedirect(reverse('expensesForm'))
    return render(request, 'expense_manager/expense_form.html', {'form': form})


@login_required
def add_file(request):
    #Comment Attempt
    form = forms.UploadFileForm()
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        # if form.is_valid():
        create_expenses_from_file(request.FILES['file'])
        messages.success(request, "File Added")
        return HttpResponseRedirect(reverse('expensesForm'))
    return render(request, 'expense_manager/add_file.html', {'form': form})


def create_expenses_from_file(file):
    wb = openpyxl.load_workbook(file)
    for sheet in wb.worksheets:
        for row in sheet.iter_rows("A2:C99"):
            if row[0].value:
                print(row[0].value)
                portfolio_first_name, portfolio_last_name = row[0].value.split(" ")
                date = datetime.datetime.strptime(row[1].value, '%m/%d/%y')
                ammount = float(row[2].value)

                portfolio, created = models.Portfolio.objects.get_or_create(first_name=portfolio_first_name, last_name=portfolio_last_name)

                expense_type, created = models.ExpenseType.objects.get_or_create(name=sheet.title, is_haamasot_expense=True)

                expense, created = models.Expense.objects.get_or_create(portfolio=portfolio, expense_type=expense_type, ammount=ammount, date=date)

                print(expense)


def file_upload(request):
    form = forms.UploadFileForm()
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            ws = openpyxl.load_workbook(file).get_sheet_by_name('Office')
            rows_from_excel = []
            for i, row in enumerate(ws.iter_rows()):
                if i == 0:
                    columns = [header.value for header in row]
                else:
                    rows_from_excel.append([value.value for value in row])
            df = pandas.DataFrame(columns=columns, data=rows_from_excel)
            df.to_json("test.json", orient='records')
            return HttpResponseRedirect(reverse('uploadFile'))
    return render(request, 'expense_manager/add_file.html', {'form': form})

expenses/expense_manager/templates/expense_manager/add_file.html
{% extends 'expense_manager/expense_manager_base_layout.html' %}
{% block content %}
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="w3-container w3-margin">
            <input type="submit" class="w3-btn w3-white w3-border w3-border-green w3-round-xlarge" value="Save Expense">
        </div>
    </form>
{% endblock %}

expenses/expense_manager/templates/expense_manager/expense_form.html
{% extends 'expense_manager/expense_manager_base_layout.html' %}
{% block head%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript">
        $(document).ready(function() {
             window.onload = function() {
             $("#id_portfolio").focus();

            };
        });
</script>
{% endblock %}

{% block content %}
    <h2>Add/Edit Expenses</h2>
    <form class="w3-third w3-container" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="w3-container w3-margin">
            <input type="submit" class="w3-btn w3-white w3-border w3-border-green w3-round-xlarge" value="Save Expense">
        </div>
        <a href="{% url 'addFile' %}">Load batch From File</a>
    </form>
{% endblock %}

expenses/expense_manager/templates/expense_manager/expense_list.html
{% extends 'expense_manager/expense_manager_base_layout.html' %}
{% block content %}
<h2>צפה בהוצאות</h2>
{% autoescape off %}
<input class="w3-margin" type="text" id="nameInput" onkeyup="filter_table_by_name()" placeholder="Search for names..">
<input class="w3-margin" type="text" id="typeInput" onkeyup="filter_table_by_type()" placeholder="Search for types..">
<form>
    {{ table }}
</form>
{% endautoescape %}
{% endblock %}

expenses/expense_manager/templates/expense_manager/expense_manager_base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <title>Expense Manager</title>
    {% block head %}{% endblock %}
</head>
<body>
<h2 class="w3-jumbo">Barak Capital - Expenses app</h2>
<ul class="w3-navbar w3-blue">
    <a href="#" onclick="w3_close()" class="w3-closenav w3-hide-large">Close &times;</a>
    <li><a href="{% url 'expensesForm' %}">Add Expense</a></li>
    <li><a href="{% url 'expenseList' %}">View Expenses</a></li>
    <li><a href="#">Edit Expenses</a></li>
    <li><a href="#">Manage Traders</a></li>
    <li><a href="#">Notes Manager</a></li>
</ul>
{% block content %}{% endblock %}

</body>
<script>
function filter_table_by_name() {
  // Declare variables
  var input, filter, table, tr, td, i;
  input = document.getElementById("nameInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}

function filter_table_by_type() {
  // Declare variables
  var input, filter, table, tr, td, i;
  input = document.getElementById("typeInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[2];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
</html>